# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"
title: Ryu Clinic
title_separator: "|"
subtitle: Acupuncture, RMT & Herbal Medicine
name: "Ryu Clinic Inc."
email:
description: >- # this means to ignore newlines until "baseurl:"
  Acupuncture, RMT & Herbal Medicine.
  ICBC, Acupuncture, RMT, TEM Herbal Medicine, Massage Therapy, Cupping, Pain Clinic, Rehabilitation, Acupoint Injection, Chronic Pain, Port Moody, Coquitlam, Tri-Cities, 한의원, 한약, 비염, 호흡기, 수면장애, 소화불량, 통증클리닉, 침치료, 포트무디
twitter_username: ryuclinic
facebook_username: ryu.clinic
github_username: jasonpa
minimal_mistakes_skin: mint
search: true
url: "https://ryu.clinic"
baseurl: #"/"
# repository: "jasonpa/rc.v2" #site repository
# teaser: #/assets/images/500x300.png #site default teaser image
# #logo: "/assets/images/LOGO.png" #88x88.png, site masthead logo
# #favicon: "/assets/images/icon/favicon.ico"
# masthead_title: # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs: true  # disabled by default
words_per_minute: 200

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Canada/Pacific # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name   : "Jiman Ryu by Ryu Clinic"
  avatar : "/assets/images/bio-photo-rc.jpg"
  bio    : ""
  location: "Port Moody, BC"
  links:
    #- label: "Website"
    #  icon: "fas fa-fw fa-link"
    #  url: "https://ryu.clinic"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/ryuclinic"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/ryu.clinic"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ryu.clinic"

# Site Footer
footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/ryuclinic"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ryu.clinic"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/ryu.clinic"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      show_date: false #포스트 날짜 표시 여부
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      toc: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Social Sharing
#
# twitter:
#   username               : ryuclinic
facebook:
  username               : ryu.clinic
  app_id                 :
  publisher              :

og_image                 : "/assets/images/LOGO-Final-Small.png" # Open Graph/Twitter default site image

instagram:
  accessToken: [REDACTED]
  clientId: [REDACTED]
  userId: ryu.clinic

# Analytics
#
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-1234567-8"
    anonymize_ip         : # true, false (default)

# Google Analytics
google_analytics:   UA-118747928-1 # Google analytics code, get your code here https://www.google.com/analytics/
google_maps_api_key: [REDACTED] # Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_place_id: ChIJQwnIMyx5hlQRGFXZSl1rBA4 #Find placeID @: https://developers.google.com/places/place-id

# Jekyll Maps https://ayastreb.me/jekyll-maps/
maps:
    google:
      api_key: [REDACTED]
      marker_cluster:
        # enabled: false

# Site Varification
google_site_verification: 2z0vgw15ccv3kth2q85z1qi7supbo9
naver-site-verification: naver0d87e8e59f87b4e75e85824b3713fcae.html
bing_site_verification:
